# Generated by Django 4.2.4 on 2023-08-29 10:41

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                (
                    "profile",
                    models.ImageField(default="author/default.jpg", upload_to="author"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateField(auto_now=True)),
                ("updated", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "short_title",
                    models.CharField(
                        blank=True, default=None, max_length=45, null=True
                    ),
                ),
                ("slug", models.CharField(default="test", max_length=150)),
                ("featured", models.BooleanField(default=False)),
                ("trending", models.BooleanField(default=False)),
                (
                    "person_featured",
                    models.JSONField(
                        blank=True, default=blogs.models.default_list, null=True
                    ),
                ),
                ("front_image", models.ImageField(upload_to="blogs")),
                ("front_image_233", models.ImageField(upload_to="blogs")),
                ("front_image_500", models.ImageField(upload_to="blogs")),
                ("description", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("english_tags", models.JSONField(default=blogs.models.default_list)),
                ("hindi_tags", models.JSONField(default=blogs.models.default_list)),
                ("language", models.CharField(default="English", max_length=10)),
                ("is_available_in_hindi", models.BooleanField(default=False)),
                ("public", models.BooleanField()),
                ("meta_description", models.CharField(max_length=200)),
                ("post_hash", models.CharField(default=0, max_length=10)),
                ("total_views", models.IntegerField(default=0)),
                ("created", models.DateField(auto_now=True)),
                ("updated", models.DateField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blogs.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blogs.category",
                    ),
                ),
                (
                    "sub_categories",
                    models.ManyToManyField(
                        related_name="sub_category", to="blogs.category"
                    ),
                ),
            ],
        ),
    ]
