# Generated by Django 4.2.4 on 2023-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="profile",
            field=models.ImageField(default="author/default.png", upload_to="author"),
        ),
    ]
