# Generated by Django 4.2.4 on 2023-08-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_author_gender_alter_author_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="gender",
        ),
    ]
