# Generated by Django 4.2.4 on 2023-08-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_author_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="author",
            name="facebook",
            field=models.CharField(default="#", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="insta",
            field=models.CharField(default="#", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="linkedin",
            field=models.CharField(default="#", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="twitter",
            field=models.CharField(default="#", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="youtube",
            field=models.CharField(default="#", max_length=255),
        ),
    ]
