# Generated by Django 4.2.4 on 2023-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_alter_category_options_author_facebook_author_insta_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default="test", max_length=150),
        ),
    ]
