# Generated by Django 4.2.4 on 2023-08-29 17:29

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="english_tags",
            field=models.JSONField(
                blank=True, default=blogs.models.default_list, null=True
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="front_image_233",
            field=models.ImageField(default="blogs/default.png", upload_to="blogs"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="front_image_500",
            field=models.ImageField(default="blogs/default.png", upload_to="blogs"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="hindi_tags",
            field=models.JSONField(
                blank=True, default=blogs.models.default_list, null=True
            ),
        ),
    ]
